update

diff --git a/exercise_session_04/exercise03/isprime_wc b/exercise_session_04/exercise03/isprime_wc
--- a/exercise_session_04/exercise03/isprime_wc
+++ b/exercise_session_04/exercise03/isprime_wc
@@ -1,6 +1,15 @@
 #!/bin/bash
 
 start=`date +%s.%N`
+if [[ ! $# -eq 1 ]]; then
+	echo "error: Not correct amount of arguments" >&2
+	exit 1
+fi
+
+re='^[0-9]+$'
+if ! [[ $1 =~ $re ]] ; then
+   echo "error: Not an integer" >&2; exit 1
+fi
 
 factoring=$(factor $1 | wc -w)
 
diff --git a/exercise_session_04/exercise04/isprime_wc_num b/exercise_session_04/exercise04/isprime_wc_num
--- a/exercise_session_04/exercise04/isprime_wc_num
+++ b/exercise_session_04/exercise04/isprime_wc_num
@@ -2,7 +2,14 @@
 
 start=`date +%s.%N`
 
+re='^[0-9]+$'
+
 while test -n "$1"; do
+	if ! [[ $1 =~ $re ]] ; then
+	   echo "error: $1 Not an integer" >&2
+	   shift
+	   continue
+	fi
 	factoring=$(factor $1 | wc -w)
 
 	if [[ $factoring -gt 2 ]]; then
diff --git a/exercise_session_04/exercise04/isprime_wc_seq b/exercise_session_04/exercise04/isprime_wc_seq
--- a/exercise_session_04/exercise04/isprime_wc_seq
+++ b/exercise_session_04/exercise04/isprime_wc_seq
@@ -2,6 +2,20 @@
 
 start=`date +%s.%N`
 
+if [[ ! $# -eq 2 ]]; then
+	echo "error: Not correct amount of arguments" >&2; exit 1
+	exit 1
+fi
+
+re='^[0-9]+$'
+if ! [[ $1 =~ $re ]] ; then
+   echo "error: First argument not an integer" >&2; exit 1
+fi
+
+if ! [[ $2 =~ $re ]] ; then
+   echo "error: Second argument not an integer" >&2; exit 1
+fi
+
 for i in $(seq $1 $2); do
 	factoring=$(factor $i | wc -w)
 
