update

diff --git a/exercise_session_04/exercise03/isprime_wc b/exercise_session_04/exercise03/isprime_wc
--- a/exercise_session_04/exercise03/isprime_wc
+++ b/exercise_session_04/exercise03/isprime_wc
@@ -2,7 +2,7 @@
 
 start=`date +%s.%N`
 if [[ ! $# -eq 1 ]]; then
-	echo "error: Not correct amount of arguments" >&2
+	echo "error: Not correct number of arguments" >&2
 	exit 1
 fi
 
diff --git a/exercise_session_04/exercise04/isprime_wc_seq b/exercise_session_04/exercise04/isprime_wc_seq
--- a/exercise_session_04/exercise04/isprime_wc_seq
+++ b/exercise_session_04/exercise04/isprime_wc_seq
@@ -3,7 +3,7 @@
 start=`date +%s.%N`
 
 if [[ ! $# -eq 2 ]]; then
-	echo "error: Not correct amount of arguments" >&2; exit 1
+	echo "error: Not correct number of arguments" >&2; exit 1
 	exit 1
 fi
 
